id: A8EC86BFB
title: Prayer for the Long Life of Dilgo Khyentsé II of Shechen, Urgyen Tenzin Jigme
  Lhundrup
type: translation
pechas:
- I46220920
- I64AC3E2F
- I890CC1CD
- IEE54466E
- IB54020B1
- I7779D711
- I9B39FF68
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - it
  - nl
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:39:30.972470
  last_modified_at: 2023-01-04 11:39:30.972489
  collections:
  - Dilgo Khyentse Yangsi Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  I46220920/56CC: 9CBB
  I64AC3E2F/94BB: 9CBB
  I890CC1CD/C094: 9CBB
  IEE54466E/D935: 9CBB
  IB54020B1/6186: 9CBB
  I7779D711/8C6F: 9CBB
  I9B39FF68/09D9: 9CBB
